apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: my-awesome-dev-bucket
  labels:
    testing.upbound.io/example-name: bucket-notification
  name: my-awesome-dev-bucket
spec:
  forProvider:
    region: us-west-1
status:
  atProvider:
    id: random-bucket-id